//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AzureSQLDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.UsersSchedules = new HashSet<UsersSchedule>();
        }
    
        public int Id { get; set; }
        public string Day { get; set; }
        public string Hour { get; set; }
    
        public virtual ICollection<UsersSchedule> UsersSchedules { get; set; }
    }
}
